name: electra_client
description: Electra University Voting System - Secure, scalable voting platform with KWASU branding
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  stream_transform: ^2.1.0
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Network & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage & Offline
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  
  # Security & Authentication
  crypto: ^3.0.3
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  
  # Device & Platform
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  connectivity_plus: ^4.0.2
  
  # Media & Files
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  video_player: ^2.7.2
  
  # Utils & Helpers
  intl: ^0.18.1
  uuid: ^4.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  dartz: ^0.10.1
  
  # Animations & UI
  animations: ^2.0.8
  flutter_staggered_animations: ^1.1.1
  
  # Charts & Data Visualization
  fl_chart: ^0.64.0
  
  # QR Code & Scanning
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  isar_generator: ^3.1.0+1
  
  # Testing
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/logos/
    
  fonts:
    - family: KWASU
      fonts:
        - asset: assets/fonts/KWASU-Regular.ttf
        - asset: assets/fonts/KWASU-Bold.ttf
          weight: 700