include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    # Allow self-reference to deprecated members
    deprecated_member_use_from_same_package: ignore
    # Treat missing required parameters as errors
    missing_required_param: error
    # Allow TODO comments in development
    todo: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - 'lib/generated/**'
    - 'build/**'

linter:
  rules:
    # Additional rules for Flutter projects
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    
    # Disable rules that conflict with code generation
    invalid_annotation_target: false
    
    # Custom rules for this project
    always_use_package_imports: true
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true