name: electra_flutter
description: A production-grade Flutter frontend for the Electra secure digital voting system
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage & Offline Support
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  
  # Security & Encryption
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0
  
  # Authentication & JWT
  jwt_decoder: ^2.0.1
  
  # Logging & Error Reporting
  logger: ^2.0.2+1
  
  # UI & Theming
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Form Handling & Validation
  formz: ^0.6.1
  
  # Utilities
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  riverpod_generator: ^2.3.9
  injectable_generator: ^2.4.1
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  isar_generator: ^3.1.0+1
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  mocktail: ^1.0.2
  
  # Linting & Analysis
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
  
  # Fonts
  fonts:
    - family: KWASU
      fonts:
        - asset: assets/fonts/KWASU-Regular.ttf
        - asset: assets/fonts/KWASU-Bold.ttf
          weight: 700
        - asset: assets/fonts/KWASU-Medium.ttf
          weight: 500