apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configuration
  namespace: electra-production
data:
  jaeger.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_binary:
            endpoint: 0.0.0.0:6832
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 8192
        send_batch_max_size: 8192
      
      memory_limiter:
        limit_mib: 512
        spike_limit_mib: 128
        check_interval: 5s
      
      resource:
        attributes:
        - key: service.namespace
          value: "electra"
          action: upsert
        - key: deployment.environment
          from_attribute: "env"
          action: upsert
    
    exporters:
      logging:
        loglevel: info
      
      # Export to Jaeger backend
      jaeger:
        endpoint: jaeger-collector:14250
        tls:
          insecure: true
      
      # Optional: Export to Prometheus for metrics
      prometheus:
        endpoint: "0.0.0.0:8889"
        const_labels:
          service: "electra-jaeger"
    
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [memory_limiter, resource, batch]
          exporters: [jaeger, logging]
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
      
      telemetry:
        logs:
          level: "info"
        metrics:
          address: 0.0.0.0:8888
---
# Standalone Jaeger configuration for Docker
jaeger-standalone.yaml: |
  # Jaeger all-in-one configuration
  collector:
    zipkin:
      host-port: :9411
  
  storage:
    type: memory
    memory:
      max-traces: 50000
  
  query:
    base-path: /
    static-files: /go/jaeger-ui/
  
  agent:
    processors:
      - model: jaeger
        protocol: compact
        workers: 50
        server:
          host-port: :6831
      - model: jaeger
        protocol: binary
        workers: 50
        server:
          host-port: :6832
  
  # Sampling configuration
  sampling:
    default_strategy:
      type: probabilistic
      param: 0.1  # 10% sampling rate
    max_traces_per_second: 100
    
  # HTTP server configuration  
  reporter:
    queue-size: 100
    batch-size: 10
    batch-timeout: 1s
  
  # Logging configuration
  log-level: info