apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: electra-django
  namespace: electra-production
  labels:
    app: electra
    component: django
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: electra-django
      component: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
    honorLabels: true
    params:
      format: ['prometheus']
  namespaceSelector:
    matchNames:
    - electra-production
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: electra-postgres
  namespace: electra-production
  labels:
    app: electra
    component: postgres
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - electra-production
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: electra-redis
  namespace: electra-production
  labels:
    app: electra
    component: redis
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - electra-production